services:
  db:
    image: postgres:15-alpine
    container_name: bocado_db
    environment:
      POSTGRES_USER: admin_bocado
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bocadodb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend:
    build: ./backend
    container_name: bocado_backend
    environment:
      DB_HOST: db
      DB_USER: admin_bocado
      DB_PASSWORD: password123
      DB_NAME: bocadodb
      DB_PORT: 5432
    depends_on:
      - db
    restart: always

  bocado-magico:
    build: .
    container_name: bocado_magico_app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: bocado_tunnel
    command: tunnel --url https://bocado-magico:443 --no-autoupdate --no-tls-verify --protocol http2
    restart: always
    depends_on:
      - bocado-magico

volumes:
  pgdata: